title: Yu-Yueh Liu
permalink: pretty
description: Yueh's personal website created with Jekyll and hosted on GitHub. It uses HTML5, SASS, Bootstrap 4, JavaScript and JQuery.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://uace.github.io
github_username: UAce

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"

plugins_dir: ./_plugins
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
jekyll_get:
  - data: github
    json: "https://api.github.com/users/UAce/repos"
    cache: false
jekyll_compose:
  auto_open: true
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

sass:
  sass_dir: _sass
  style: compressed

# Config for image tag
image:
  source: assets/images
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    half:
      width: 400
      height: 400

# Social links
social_links:
  github: UAce
  linkedin: in/yu-yueh-liu-667696121/
  facebook: YuYuehLiu
  email: yu-yueh@hotmail.com

# canvas titles
canvas:
  home: Welcome
  articles: What's new?
  resume: Find Out More
  about: My Passions & Interests

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README
