title: Your awesome title
email: your-email@example.com
permalink: pretty
description: Yu-Yueh Liu's personal website as a summer project.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://uace.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: UAce

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
theme: minima
plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: "https://api.github.com/users/UAce/repos"
    cache: false
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README
