title: Yu-Yueh Liu
permalink: pretty
description: My personal website - Just a summer project.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://uace.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
github_username: UAce

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins_dir: ./_plugins
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
jekyll_get:
  - data: github
    json: "https://api.github.com/users/UAce/repos"
    cache: false
jekyll_compose:
  auto_open: true

sass:
  sass_dir: _sass
  style: compressed

# Config for image tag
image:
  source: assets/images
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    half:
      width: 400
      height: 400

# Social links
social_links:
  github: UAce
  linkedin: in/yu-yueh-liu-667696121/
  facebook: YuYuehLiu
  email: yu-yueh@hotmail.com

# canvas titles
canvas:
  home: Welcome.
  resume: Find Out More.
  about: My Passions & Interests.

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README
