source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "json"
gem "hash-joiner"
gem "html-proofer"
gem "jemoji"
gem "mini_magick"
gem "kramdown", "~> 2.4.0"
gem "kramdown-parser-gfm", "~> 1.1"
gem "i18n", "~> 1.0"
gem "bootstrap", "~> 4.4.1"
gem "concurrent-ruby", "~> 1.1.6"
gem "execjs", "~> 2.7.0"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-autoprefixer"
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-compose"
  gem "jekyll-minifier"
  gem "jekyll-sass-converter", "~> 3.0.0"
  gem "jekyll-watch", "~> 2.2"
  gem "jekyll-mentions", "~> 1.6"
  gem "webrick", "~> 1.8"
end
